### PR TITLE
Added London JS community to the list

### PR DESCRIPTION
**Pull request by ifraixedes**

### CODE REVIEW

**Comment by iancrowther** [comment]
lgtm

**Comment by jkbits1** [comment]
great

**Comment by iancrowther** [comment]
thanks @ifraixedes - prob best not to merge your own PR's :-)

Am trying to bring in a merge policy of x2 orgs + 48hr window

**Comment by ifraixedes** [comment]
Sorry guys, I use to work in different workflow, "send -> somebody review and approve -> owner merge"

I did not know the one here, I know now :smiley: 

@iancrowther that policy make more sense for community projects, so :+1:

**Comment by iancrowther** [comment]
I literally just dropped it in without any consultation! will announce tonight

**Pull request merged**
